### ISSUE TITLE
Use <a> instead of onclick event

### ISSUE THREAD

**Issue by SkyZH** [wangzhihao1995/BlackMarket#1]
https://github.com/wangzhihao1995/BlackMarket/blob/master/black_market/templates/index.html#L88

```
<div class="col-md-6" onclick="openPostPgae('{{post.id}}');">
```

We could replace `<div>` with `<a>` and apply `display: block` to this tag.

```
<a class="col-md-6" style="display: block" href="/posts/{{post.id}}">
```

By the way, there is `show` helper class in bootstrap 3, which add attribute `display: block` to an element.

**Comment by wangzhihao1995** [comment]
Hello. Sorry for replying you so late and ... forgetting to reply you so many times. I saw the issue you made I tried it before. But somehow it didn't work as I expected. I thought I could figure it out and then reply but I kept it unresolved all along. Anyway, thanks for your advice and please forgive me for not replying you.

**Comment by SkyZH** [comment]
Maybe i will create a pull request if I could afford time to write code and
debug it. Hope your project run well this fall.

**Comment by wangzhihao1995** [comment]
Thank you. I plan to use wechat mini program instead of primitive web.
